# Generated by Django 3.2.3 on 2021-06-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='function',
            field=models.CharField(default='Founder', max_length=30),
        ),
    ]
